import Head from "next/head";
import Image from "next/image";
import styles from "../styles/home.module.scss";
import Search from "./components/Search";

export default function Home() {
  const description =
    "Discover when your<br> favorite charachters<br> are on screen!";
  const quantity = "Browse over +100.000 characters";
  return (
    <div className={styles.container}>
      <Head>
        <title>
          Hisashiburi - found the episodes your favorites characters appears
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
        <div className={styles.banner}>
          <h1>
            Discover when your
            <br /> favorite charachters
            <br /> are on screen!
          </h1>
          <h3>{quantity}</h3>
          <Search />
        </div>
        <div>results</div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
