import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import styles from "../styles/home.module.scss";
import { useRouter } from "next/router";

//Components
import Search from "./components/Search";
import Character from "./components/Character";
import HomePage from "./components/HomePage";

// type the props of the getStaticProps rocket seat
// pass the data in two ways, the percent and the time like 00:00:00
// change the ui like in figma
// add layout or head rocketseat way for our nav
// fuzzy search
// deploy

type Characters = {
  id: number;
  name: string;
  lastName: string;
  icon: string;
};


export default function Home() {
  const description =
  "Discover when your<br> favorite charachters<br> are on screen!";
  const quantity = "Browse over +100.000 characters";
  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>
          Hisashiburi - found the episodes your favorites characters appears
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
{/* <HomePage /> */}
// const [characters, setCharacters] = useState<Characters[]>([]);
// const router = useRouter();
// let name = "Itachi Uchiha";
// let gaara = "Sabaku no Gaara";
// let minato = "Minato Namikaze";
// let icon = "/images/itachi.jpg";
// let gaaraUrl = "/images/gaara.jpg";
// let minatoUrl = "/images/minato.jpg";

{/* <main className={styles.home}>
<div className={styles.banner}>
<Image
className={styles.bannerImage}
src="/images/header-image.png"
layout="fill"
objectFit="cover"
quality="100"
/>
<h1>
Discover when your
<br /> favorite characters
<br /> are on screen!
    </h1>
    <h3>{quantity}</h3>
    <Search setCharacters={setCharacters} />
  </div>

  <div className={styles.results}>
    {characters.map((char) => {
      return (
        <div key={char.id}>
          <Link href={`/?character=${char.id}`} as={`/characters/${char.id}`}>
            <a>
              <Character name={char.name} icon={char.icon} />
            </a>
          </Link>
          {char.name}
        </div>
      );
    })} */}
    {/* <Character name={gaara} icon={gaaraUrl} />
    <Character name={minato} icon={minatoUrl} />
    <Character name={name} icon={icon} />
    <Character name={gaara} icon={gaaraUrl} />
    <Character name={minato} icon={minatoUrl} />
    <Character name={name} icon={icon} />
    <Character name={gaara} icon={gaaraUrl} />
    <Character name={minato} icon={minatoUrl} />
    <Character name={name} icon={icon} />
    <Character name={gaara} icon={gaaraUrl} />
    <Character name={minato} icon={minatoUrl} /> */}
  {/* </div> */}
  
{/* </main> */}

{/* <Modal isOpen={!!router.query.character}>
  <h1>hi</h1>
</Modal> */}