import Head from "next/head";
import Image from "next/image";
import styles from "../styles/home.module.scss";
//Components
import Search from "./components/Search";
import Character from "./components/Character";

export default function Home() {
  let name = "Itachi Uchiha";
  let gaara = "Sabaku no Gaara";
  let minato = "Minato Namikaze";

  let imageUrl = "/images/itachi.jpg";
  let gaaraUrl = "/images/gaara.jpg";
  let minatoUrl = "/images/minato.jpg";

  const description =
    "Discover when your<br> favorite charachters<br> are on screen!";
  const quantity = "Browse over +100.000 characters";

  return (
    <div className={styles.container}>
      <Head>
        <title>
          Hisashiburi - found the episodes your favorites characters appears
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
        <div className={styles.banner}>
          <Image
            className={styles.bannerImage}
            src="/images/header-image.png"
            layout="fill"
            objectFit="cover"
            quality="100"
          />
          <h1>
            Discover when your
            <br /> favorite characters
            <br /> are on screen!
          </h1>
          <h3>{quantity}</h3>
          <Search />
        </div>

        <div className={styles.results}>
          <Character name={name} imageUrl={imageUrl} />
          <Character name={gaara} imageUrl={gaaraUrl} />
          <Character name={minato} imageUrl={minatoUrl} />
          <Character name={name} imageUrl={imageUrl} />
          <Character name={gaara} imageUrl={gaaraUrl} />
          <Character name={minato} imageUrl={minatoUrl} />
          <Character name={name} imageUrl={imageUrl} />
          <Character name={gaara} imageUrl={gaaraUrl} />
          <Character name={minato} imageUrl={minatoUrl} />
          <Character name={name} imageUrl={imageUrl} />
          <Character name={gaara} imageUrl={gaaraUrl} />
          <Character name={minato} imageUrl={minatoUrl} />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
